fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 100"
fsclish -c "delete networking ipbr ipbr-id 100"
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 101"
fsclish -c "delete networking ipbr ipbr-id 101"
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 102"
fsclish -c "delete networking ipbr ipbr-id 102                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 103"
fsclish -c "delete networking ipbr ipbr-id 103                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 104"
fsclish -c "delete networking ipbr ipbr-id 104                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 105"
fsclish -c "delete networking ipbr ipbr-id 105                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 106"
fsclish -c "delete networking ipbr ipbr-id 106                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 107"
fsclish -c "delete networking ipbr ipbr-id 107                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 108"
fsclish -c "delete networking ipbr ipbr-id 108                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 109"
fsclish -c "delete networking ipbr ipbr-id 109                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 110"
fsclish -c "delete networking ipbr ipbr-id 110                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 111"
fsclish -c "delete networking ipbr ipbr-id 111                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 112"
fsclish -c "delete networking ipbr ipbr-id 112                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 113"
fsclish -c "delete networking ipbr ipbr-id 113                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 114"
fsclish -c "delete networking ipbr ipbr-id 114                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 115"
fsclish -c "delete networking ipbr ipbr-id 115                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 116"
fsclish -c "delete networking ipbr ipbr-id 116                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 117"
fsclish -c "delete networking ipbr ipbr-id 117                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 118"
fsclish -c "delete networking ipbr ipbr-id 118                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 119"
fsclish -c "delete networking ipbr ipbr-id 119                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 120"
fsclish -c "delete networking ipbr ipbr-id 120                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 121"
fsclish -c "delete networking ipbr ipbr-id 121                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 122"
fsclish -c "delete networking ipbr ipbr-id 122                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 147"
fsclish -c "delete networking ipbr ipbr-id 147                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 148"
fsclish -c "delete networking ipbr ipbr-id 148                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 149"
fsclish -c "delete networking ipbr ipbr-id 149                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 150"
fsclish -c "delete networking ipbr ipbr-id 150                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 151"
fsclish -c "delete networking ipbr ipbr-id 151                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 152"
fsclish -c "delete networking ipbr ipbr-id 152                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 153"
fsclish -c "delete networking ipbr ipbr-id 153                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 154"
fsclish -c "delete networking ipbr ipbr-id 154                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 155"
fsclish -c "delete networking ipbr ipbr-id 155                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 156"
fsclish -c "delete networking ipbr ipbr-id 156                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 157"
fsclish -c "delete networking ipbr ipbr-id 157                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 158"
fsclish -c "delete networking ipbr ipbr-id 158                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 159"
fsclish -c "delete networking ipbr ipbr-id 159                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 160"
fsclish -c "delete networking ipbr ipbr-id 160                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 161"
fsclish -c "delete networking ipbr ipbr-id 161                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 162"
fsclish -c "delete networking ipbr ipbr-id 162                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 163"
fsclish -c "delete networking ipbr ipbr-id 163                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 164"
fsclish -c "delete networking ipbr ipbr-id 164                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 165"
fsclish -c "delete networking ipbr ipbr-id 165                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 166"
fsclish -c "delete networking ipbr ipbr-id 166                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 167"
fsclish -c "delete networking ipbr ipbr-id 167                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 168"
fsclish -c "delete networking ipbr ipbr-id 168                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 169"
fsclish -c "delete networking ipbr ipbr-id 169                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 170"
fsclish -c "delete networking ipbr ipbr-id 170                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 171"
fsclish -c "delete networking ipbr ipbr-id 171                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 172"
fsclish -c "delete networking ipbr ipbr-id 172                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 173"
fsclish -c "delete networking ipbr ipbr-id 173                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 174"
fsclish -c "delete networking ipbr ipbr-id 174                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 175"
fsclish -c "delete networking ipbr ipbr-id 175                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 176"
fsclish -c "delete networking ipbr ipbr-id 176                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 177"
fsclish -c "delete networking ipbr ipbr-id 177                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 178"
fsclish -c "delete networking ipbr ipbr-id 178                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 179"
fsclish -c "delete networking ipbr ipbr-id 179                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 180"
fsclish -c "delete networking ipbr ipbr-id 180                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 181"
fsclish -c "delete networking ipbr ipbr-id 181                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 182"
fsclish -c "delete networking ipbr ipbr-id 182                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 183"
fsclish -c "delete networking ipbr ipbr-id 183                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 184"
fsclish -c "delete networking ipbr ipbr-id 184                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 185"
fsclish -c "delete networking ipbr ipbr-id 185                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 186"
fsclish -c "delete networking ipbr ipbr-id 186                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 187"
fsclish -c "delete networking ipbr ipbr-id 187                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 188"
fsclish -c "delete networking ipbr ipbr-id 188                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 189"
fsclish -c "delete networking ipbr ipbr-id 189                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 190"
fsclish -c "delete networking ipbr ipbr-id 190                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 191"
fsclish -c "delete networking ipbr ipbr-id 191                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 192"
fsclish -c "delete networking ipbr ipbr-id 192                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 193"
fsclish -c "delete networking ipbr ipbr-id 193                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 194"
fsclish -c "delete networking ipbr ipbr-id 194                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 195"
fsclish -c "delete networking ipbr ipbr-id 195                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 196"
fsclish -c "delete networking ipbr ipbr-id 196                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 197"
fsclish -c "delete networking ipbr ipbr-id 197                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 198"
fsclish -c "delete networking ipbr ipbr-id 198                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 199"
fsclish -c "delete networking ipbr ipbr-id 199                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 200"
fsclish -c "delete networking ipbr ipbr-id 200                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 201"
fsclish -c "delete networking ipbr ipbr-id 201                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 202"
fsclish -c "delete networking ipbr ipbr-id 202                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 203"
fsclish -c "delete networking ipbr ipbr-id 203                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 204"
fsclish -c "delete networking ipbr ipbr-id 204                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 205"
fsclish -c "delete networking ipbr ipbr-id 205                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 206"
fsclish -c "delete networking ipbr ipbr-id 206                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 207"
fsclish -c "delete networking ipbr ipbr-id 207                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 208"
fsclish -c "delete networking ipbr ipbr-id 208                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 209"
fsclish -c "delete networking ipbr ipbr-id 209                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 210"
fsclish -c "delete networking ipbr ipbr-id 210                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 211"
fsclish -c "delete networking ipbr ipbr-id 211                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 212"
fsclish -c "delete networking ipbr ipbr-id 212                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 213"
fsclish -c "delete networking ipbr ipbr-id 213                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 214"
fsclish -c "delete networking ipbr ipbr-id 214                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 215"
fsclish -c "delete networking ipbr ipbr-id 215                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 216"
fsclish -c "delete networking ipbr ipbr-id 216                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 217"
fsclish -c "delete networking ipbr ipbr-id 217                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 218"
fsclish -c "delete networking ipbr ipbr-id 218                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 219"
fsclish -c "delete networking ipbr ipbr-id 219                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 220"
fsclish -c "delete networking ipbr ipbr-id 220                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 221"
fsclish -c "delete networking ipbr ipbr-id 221                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 222"
fsclish -c "delete networking ipbr ipbr-id 222                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 223"
fsclish -c "delete networking ipbr ipbr-id 223                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 224"
fsclish -c "delete networking ipbr ipbr-id 224                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 225"
fsclish -c "delete networking ipbr ipbr-id 225                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 226"
fsclish -c "delete networking ipbr ipbr-id 226                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 227"
fsclish -c "delete networking ipbr ipbr-id 227                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 228"
fsclish -c "delete networking ipbr ipbr-id 228                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 229"
fsclish -c "delete networking ipbr ipbr-id 229                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 230"
fsclish -c "delete networking ipbr ipbr-id 230                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 231"
fsclish -c "delete networking ipbr ipbr-id 231                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 232"
fsclish -c "delete networking ipbr ipbr-id 232                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 233"
fsclish -c "delete networking ipbr ipbr-id 233                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 234"
fsclish -c "delete networking ipbr ipbr-id 234                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 235"
fsclish -c "delete networking ipbr ipbr-id 235                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 236"
fsclish -c "delete networking ipbr ipbr-id 236                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 237"
fsclish -c "delete networking ipbr ipbr-id 237                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 238"
fsclish -c "delete networking ipbr ipbr-id 238                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 239"
fsclish -c "delete networking ipbr ipbr-id 239                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 240"
fsclish -c "delete networking ipbr ipbr-id 240                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 241"
fsclish -c "delete networking ipbr ipbr-id 241                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 242"
fsclish -c "delete networking ipbr ipbr-id 242                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 243"
fsclish -c "delete networking ipbr ipbr-id 243                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 245"
fsclish -c "delete networking ipbr ipbr-id 245                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 244"
fsclish -c "delete networking ipbr ipbr-id 244                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 247"
fsclish -c "delete networking ipbr ipbr-id 247                                                       "
fsclish -c "delete networking ipro ip-address 191.251.10.10 iface ethtest20 owner /QNUP-0 ipbr-id 248"
fsclish -c "delete networking ipbr ipbr-id 248"
fsclish -c "delete networking qos-profile idsp idsp-id 1"
fsclish -c "delete networking qos-profile idsp idsp-id 2"
fsclish -c "delete networking qos-profile idsp idsp-id 10"
fsclish -c "delete networking qos-profile iphb iphb-id 1"
fsclish -c "delete networking qos-profile iphb iphb-id 2" 
fsclish -c "delete networking qos-profile iphb iphb-id 10"
fsclish -c "delete networking networking address /QNUP-0 iface ethtest20 ip-address 191.251.10.10/28"