export const GROUP_CREATE_SUCCESS= 'GROUP_CREATE_SUCCESS';
export const GROUPS_READ_SUCCESS= 'GROUPS_READ_SUCCESS';
export const GROUP_UPDATE_SUCCESS= 'GROUP_UPDATE_SUCCESS';
//export const SET_SELECTED_SKILL_CATEGORY = 'SET_SELECTED_SKILL_CATEGORY';


